### ISSUE TITLE
configurable log messages levels parsing

### ISSUE THREAD

**Issue by luber** [tilt-dev/tilt-extensions#533] opened 2023-10-22 22:11 UTC
When I look at k8s resource logs on web UI - it does not show any Warnings, even if there is a Warning log message:
<img width="894" alt="image" src="https://github.com/tilt-dev/tilt-extensions/assets/3791692/1998b5ea-0c3d-4ee3-8e60-3b917dd2c4c3">

It looks like Tilk doesn't recognize this. It would be nice to be able to configure regex for each log level for k8s resource so Tilt can understand the level and filter/highlight them on web ui.

**Comment by nicks** [comment] 2023-10-23 15:56
thanks for the report! i'm going to mark this as a duplicate of https://github.com/tilt-dev/tilt/issues/4762

**Closed by nicks** 2023-10-23 15:56 UTC
