### ISSUE TITLE
helm_resource ignores --context

### ISSUE THREAD

**Issue by alanchrt** [tilt-dev/tilt-extensions#395] opened 2022-05-06 16:14 UTC
I just recently switched to the new `helm_resource` from `helm_remote`.

On our team, we've built a wrapper CLI for devs that uses `tilt` under the hood. When we call tilt, we always pass `--context <whatever>` to decouple the commands from whatever kubectl context they have set on their machine. Tilt should always run against their development cluster.

However, yesterday, I was debugging an issue in production and had switched to a production kubectl context. I ran `tilt up --context <mycluster>` and my `helm_resource` attempted to deploy to the production cluster instead of `mycluster`.

Thankfully, in this case, our production resources were helm-managed in a different namespace than the one tilt was trying to deploy to (`default`), so deploy failed.

```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: <ResourceType> "<resouce>" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "default": current value is "<production-namespace>"
```

Repro:

1. Create a `Tiltfile` with a `helm_resource`
1. `kubectl config use-context context-1`
2. `tilt up --context context-2`
3. Watch tilt deploy the `helm_resource` to context-1

```
❯ tilt version
v0.28.1, built 2022-05-01
```

**Comment by landism** [comment] 2022-05-06 16:51
Thanks for filing! This will be taken care of by https://github.com/tilt-dev/tilt/issues/5703 since `helm_resource` is powered by `k8s_custom_deploy`. I'm closing this issue as a dupe of that one, but feel free to re-open if that issue is missing anything.

**Closed by landism** 2022-05-06 16:51 UTC

**Comment by alanchrt** [comment] 2022-05-06 16:58
Thank you!!

**Comment by amkartashov** [comment] 2023-03-10 13:05
This bug is not fixed, no changes in k8s_custom_deploy will do, because it does not affect how you create commands with helm and kubectl.
