### ISSUE TITLE
Resource Deps for k8s_yaml?

### ISSUE THREAD

**Issue by alikleit** [tilt-dev/tilt-extensions#595] opened 2024-08-14 10:11 UTC
Is there a way to accomplish something like:
```
k8s_yaml('file.yaml', resource_deps=["service-operator"])
```

where `service-operator` is a helm_resource

**Comment by nicks** [comment] 2024-08-14 16:00
not today, only on k8s_resource, marking this as a duplicate of https://github.com/tilt-dev/tilt/issues/3265

**Closed by nicks** 2024-08-14 16:00 UTC
