### ISSUE TITLE
[Feature] Split the resources created by `helm_resource` based on Kubernetes object labels

### ISSUE THREAD

**Issue by rrmistry** [tilt-dev/tilt-extensions#495] opened 2023-05-10 19:03 UTC
## Our problem:

- We have multiple helm charts that we deploy via Tilt simultaneously
- We use `helm_resource` in our Tiltfile because the native [`helm`](https://docs.tilt.dev/api.html#api.helm)/[`k8s_yaml`](https://docs.tilt.dev/api.html#api.k8s_yaml) functionality does not allow to add Tilt labels to resources
  - See issue https://github.com/tilt-dev/tilt/issues/6106 for more info
- We need this to more easily split the resources within the multiple helm charts from each other
- With `helm_resource` we can assign Tilt labels, however, all of our micro-services now get grouped into only one Tilt resource
- This also means that all of our micro-services output their logs in one view which makes it hard to decipher and diagnose problems

## Our request:

- We already add a lot of labels to our Kubernetes objects that could be used to split the resources from Helm into sub-resources in Tilt via `helm_resource`
- Is it possible to add a new function argument to `helm_resource` to split resources by labels?
  - For e.g. `app.kubernetes.io/component` or even a custom specified label name
- This would make it significantly easier to see all the microservices within a given Tilt group (i.e. Tilt Label) but also see Kubernetes resources that are further sub-grouped (i.e. K8s Label)

_____

Really appreciate the product though 👌

It is saving us huge amounts of time and this is greatly appreciated 🙏

**Comment by nicks** [comment] 2023-05-13 01:40
Thanks for the report! I'm going to mark this as a duplicate of https://github.com/tilt-dev/tilt/issues/5944 which kind of gets at the same thing

**Closed by nicks** 2023-05-13 01:40 UTC
